"""Install command — first-run project setup wizard."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from vstack.cli.base import BaseCommand, CommandContext
from vstack.cli.constants import Colors
from vstack.cli.init import InitCommand

if TYPE_CHECKING:
    from vstack.cli.service import CommandService


class InstallCommand(BaseCommand):
    """First-run project setup wizard.

    Seeds ``.vstack/`` scaffold and per-agent guidance templates from package
    templates (additive only), then delegates artifact generation to
    :class:`~vstack.cli.init.InitCommand`.
    """

    def __init__(self, service: CommandService) -> None:
        self._service = service

    @staticmethod
    def _seed_project(
        *,
        project_root: Path,
        templates_root: Path,
        colors,
        dry_run: bool,
    ) -> None:
        """Seed project-scope files from package templates (additive only).

        Two sources are seeded into *project_root*:

        1. ``_templates/project/`` — base ``.vstack/`` scaffold (config, tmp/).
        2. ``_templates/agents/{name}/artifacts/`` — per-role guidance templates
           seeded to ``.vstack/templates/{name}/artifacts/``.

        Existing files are never modified.
        """
        prefix = f"{colors.DIM}[dry-run]{colors.RESET} " if dry_run else ""

        def _seed_file(src_file: Path, dst: Path) -> None:
            if dst.exists():
                rel = dst.relative_to(project_root)
                print(
                    f"  {prefix}{colors.YELLOW}↷{colors.RESET}  {rel}"
                    f"  {colors.DIM}skipped — already exists{colors.RESET}"
                )
            else:
                rel = dst.relative_to(project_root)
                print(
                    f"  {prefix}{colors.GREEN}✓{colors.RESET}  "
                    f"{colors.BOLD}{rel}{colors.RESET}"
                    f"  {colors.DIM}seeded{colors.RESET}"
                )
                if not dry_run:
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    dst.write_text(src_file.read_text(encoding="utf-8"), encoding="utf-8")

        # 1. Base .vstack/ scaffold
        project_seed = templates_root / "project"
        if project_seed.exists():
            for src_file in sorted(project_seed.rglob("*")):
                if src_file.is_file():
                    _seed_file(src_file, project_root / src_file.relative_to(project_seed))

        # 2. Per-agent artifacts → .vstack/templates/{agent}/artifacts/
        agents_root = templates_root / "agents"
        if agents_root.exists():
            for agent_dir in sorted(agents_root.iterdir()):
                if not agent_dir.is_dir():
                    continue
                artifacts_dir = agent_dir / "artifacts"
                if not artifacts_dir.exists():
                    continue
                for src_file in sorted(artifacts_dir.rglob("*")):
                    if src_file.is_file():
                        rel = src_file.relative_to(artifacts_dir)
                        dst = (
                            project_root
                            / ".vstack"
                            / "templates"
                            / agent_dir.name
                            / "artifacts"
                            / rel
                        )
                        _seed_file(src_file, dst)

    @staticmethod
    def _write_vstack_gitignore(*, project_root: Path, dry_run: bool) -> None:
        """Write (or overwrite) ``.vstack/.gitignore`` with generated content.

        Unlike seed files, ``.gitignore`` is always regenerated on install so it
        stays current with changes to the ``.vstack/`` directory layout.  The file
        ignores scratch/temporary output under ``.vstack/tmp/``, runtime audit
        logs under ``.vstack/logs/``, and planner-run session cache files under
        ``.vstack/memories/session/`` while keeping all other committed files —
        ``.gitignore`` itself, ``config.yaml``,
        ``vstack.json``, and the seeded ``templates/`` tree — tracked by Git.
        """
        content = (
            "# Generated by vstack install — do not edit manually.\n"
            "tmp/\n"
            "logs/\n"
            "memories/session/\n"
        )
        gitignore = project_root / ".vstack" / ".gitignore"
        if not dry_run:
            gitignore.parent.mkdir(parents=True, exist_ok=True)
            gitignore.write_text(content, encoding="utf-8")

    def run(
        self,
        *,
        context: CommandContext,
    ) -> int:
        """Execute the install wizard and return a process-style status code.

        For local installs, seeds ``.vstack/`` scaffold and per-agent guidance
        templates (additive only) before generating ``.github/`` artifacts.
        Global installs skip seeding and generate artifacts directly.
        """
        install_dir = context.require_install_dir("install")
        use_global = getattr(context.args, "use_global", False)
        dry_run = getattr(context.args, "dry_run", False)
        colors = Colors

        if not use_global:
            project_root = install_dir.parent
            print(f"\n  {colors.BOLD}Seeding project files{colors.RESET}")
            InstallCommand._seed_project(
                project_root=project_root,
                templates_root=self._service.root,
                colors=colors,
                dry_run=dry_run,
            )
            InstallCommand._write_vstack_gitignore(
                project_root=project_root,
                dry_run=dry_run,
            )

        print(f"\n  {colors.BOLD}Generating .github/ artifacts{colors.RESET}")
        return InitCommand.execute(
            self._service,
            install_dir,
            only=context.only,
            excluded_names=context.excluded_names,
            force=getattr(context.args, "force", False),
            force_names=getattr(context.args, "force_names", None),
            adopt_names=getattr(context.args, "adopt_name", None),
            update=getattr(context.args, "update", False),
            dry_run=dry_run,
        )
